apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: kubeflow-extension
spec:
  storageClassName: gold-tanzu-kubernetes-storage-policy
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi