apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-ml-pipeline-nb-$namespace
  namespace: kubeflow
spec:
  roleRef:
    kind: ServiceRole
  subjects:
    name: ml-pipeline-services
    - properties:
        source.principal: cluster.local/ns/$namespace/sa/default-editor