apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"app":"mixer","istio":"rbac","kustomize.component":"istio-crds","package":"istio.io.mixer"},"name":"servicerolebindings.rbac.istio.io"},"spec":{"additionalPrinterColumns":[{"JSONPath":".spec.roleRef.name","description":"The name of the ServiceRole object being referenced","name":"Reference","type":"string"},{"JSONPath":".metadata.creationTimestamp","description":"CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.\n\nPopulated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata","name":"Age","type":"date"}],"group":"rbac.istio.io","names":{"categories":["istio-io","rbac-istio-io"],"kind":"ServiceRoleBinding","plural":"servicerolebindings","singular":"servicerolebinding"},"scope":"Namespaced","versions":[{"name":"v1alpha1","served":true,"storage":true}]}}
  creationTimestamp: "2020-09-28T11:12:12Z"
  generation: 1
  labels:
    app: mixer
    istio: rbac
    kustomize.component: istio-crds
    package: istio.io.mixer
  name: servicerolebindings.rbac.istio.io
  resourceVersion: "10074"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/servicerolebindings.rbac.istio.io
  uid: b4201c99-1114-457e-b175-1eb2c5de2183
spec:
  conversion:
    strategy: None
  group: rbac.istio.io
  names:
    categories:
      - istio-io
      - rbac-istio-io
    kind: ServiceRoleBinding
    listKind: ServiceRoleBindingList
    plural: servicerolebindings
    singular: servicerolebinding
  preserveUnknownFields: true
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The name of the ServiceRole object being referenced
          jsonPath: .spec.roleRef.name
          name: Reference
          type: string
        - description: |-
            CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

            Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      served: true
      storage: true
status:
  acceptedNames:
    categories:
      - istio-io
      - rbac-istio-io
    kind: ServiceRoleBinding
    listKind: ServiceRoleBindingList
    plural: servicerolebindings
    singular: servicerolebinding
  conditions:
    - lastTransitionTime: "2020-09-28T11:12:12Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2020-09-28T11:12:12Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1alpha1